### PR TITLE
Allow older versions of gettext

### PR DESCRIPTION
**Pull request by tresf**
Gettext 0.18.3 works just fine and lowers the requirements for older build systems.
@hartwork FYI, partially reverts 01c7745.  
Tested on Ubuntu 14.04.

### CODE REVIEW

**Comment by hartwork** [comment]
I think I did have a reason back then, but I don't remember, sorry. With my 0.19.8.1 here I rely on you for testing. No objections from my side.

**Comment by hartwork** [comment]
Please check #25 for why I bumped to gettext 0.19.x back then. 0.18.3 may still do, but I rely on you for testing.

**Comment by tresf** [comment]
@hartwork:

```diff
ubuntu@ubuntu1404:~/ladspa$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

```diff
ubuntu@ubuntu1404:~/ladspa$ gettext --version
+gettext (GNU gettext-runtime) 0.18.3
Copyright (C) 1995-1997, 2000-2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

Mine (red) versus yours (green)
```diff
+ Copying file ABOUT-NLS
  Copying file config.rpath
- Creating directory m4
  Copying file m4/codeset.m4
+ Copying file m4/extern-inline.m4
  Copying file m4/fcntl-o.m4
  Copying file m4/gettext.m4
  Copying file m4/glibc2.m4
  Copying file m4/glibc21.m4
  Copying file m4/iconv.m4
  Copying file m4/intdiv0.m4
  Copying file m4/intl.m4
  Copying file m4/intldir.m4
  Copying file m4/intlmacosx.m4
  Copying file m4/intmax.m4
  Copying file m4/inttypes-pri.m4
  Copying file m4/inttypes_h.m4
  Copying file m4/lcmessage.m4
  Copying file m4/lib-ld.m4
  Copying file m4/lib-link.m4
  Copying file m4/lib-prefix.m4
  Copying file m4/lock.m4
  Copying file m4/longlong.m4
  Copying file m4/nls.m4
  Copying file m4/po.m4
  Copying file m4/printf-posix.m4
  Copying file m4/progtest.m4
  Copying file m4/size_max.m4
  Copying file m4/stdint_h.m4
  Copying file m4/threadlib.m4
  Copying file m4/uintmax_t.m4
  Copying file m4/visibility.m4
  Copying file m4/wchar_t.m4
  Copying file m4/wint_t.m4
  Copying file m4/xsize.m4
  Copying file po/Makefile.in.in
  Copying file po/Makevars.template
  Copying file po/Rules-quot
  Copying file po/boldquot.sed
  Copying file po/en@boldquot.header
  Copying file po/en@quot.header
  Copying file po/insert-header.sin
  Copying file po/quot.sed
- Copying file po/remove-potcdate.sin
```

* `ABOUT-NLS` has since been removed by you in 236bda4.
* `remove-potcdate.sin` I can't find any info on, but [here's a mirror](https://github.com/coreos/grub/blob/master/po/remove-potcdate.sin).
* `extern-inline.m4` I'm having trouble locating as well.

I don't know this build system (at all) so I hope this provides enough information for a decision.  If not, let me know and I can dig some more information.

**Comment by hartwork** [comment]
For `extern-inline.m4`: http://git.savannah.gnu.org/cgit/gettext.git/tree/gettext-runtime/m4/extern-inline.m4

**Pull request merged**
